### ISSUE TITLE
[Request] Only view deathrattle

### ISSUE THREAD

**Issue by Cyberdr3am** [batstyx/Graveyard#14]
Hi thx for updating this but can you ad an option to view only the deathrattle.
Just an option to remove the graveyard to just see other section.
Thx

**Comment by batstyx** [comment]
I'm assuming you're talking about something other than turning off the Player Graveyard view and just having the Deathrattle view active.

Can you expand on the scenario you're describing?
Is it any (or none) of the following:-

1. Player
2. Opponent
3. Independent of any Deathrattle effect card being in deck
4. Dependent on a specific card being in deck 

Any further details would be useful.

**Comment by Cyberdr3am** [comment]
Thx for the reply.
With this plugin i can see all minion died for me and the opponent. I have only activate deathrattle to see how many card with deathrattle have died during the game ( it's for the SELFISH SHELLFISH card ).
I track it for my opponent to.
I just whant to see all deathrattle card with this plugin not all died minion on two section ( Graveyard and deathrattle )
If i can remove the Graveyard section and keep other category for me and other player.
Hope I was clear if not I can take a screenshot.

Thx

**Comment by batstyx** [comment]
Hopefully the Opponent Graveyard view is what you're after. I can see how it would be useful against Shellfish decks.
I'm still not clear on the player scenario that isn't already covered by the plugin functionality.
Maybe it would be useful for you to post some deck codes?
