### ISSUE TITLE
[BUG] The plugins lost config

### ISSUE THREAD

**Issue by Cyberdr3am** [batstyx/Graveyard#15]
Hi,

When i change the config to move the UI and change some settings and when i restart Hearthstone Deck Tracker twice or the game i lost all my config.
I try to reinstall the plugin and try other thing but every 2/3 launch i lost all the plugin config
Can you explain me how i can fix this ? 

Thx

**Comment by batstyx** [comment]
I'm assuming you're running HDT 1.7.12 and Graveyard 1.9.6 or 1.10?

If this is an upgrade from a much older version of Graveyard it might be there's an old setting that's preventing the config from loading and/or saving properly.

While HDT isn't running, try deleting `%appdata%\HearthstoneDeckTracker\Graveyard.xml`

If that doesn't work try looking at `hdt_log.txt` in the `%appdata%\HearthstoneDeckTracker\Logs` directory. 
Check any errors relating to Graveyard, there should be just load and save events if nothing's wrong. 

`hdt_log.txt` is for the most recent or currently running HDT session. 
You may need to also check a few of the most recent `hdt_log_#.txt` files as well.

**Comment by Cyberdr3am** [comment]
Thx for the reply.
I have try to delete Graveyard.xml from the folder. ( i use the last Graveyard version and last HDT )
I try few times today and if it's fixed i close this ticket.
