### ISSUE TITLE
Hearthstone Deck Tracker Plugin Location Reset Issue

### ISSUE THREAD

**Issue by Cyberdr3am** [batstyx/Graveyard#29]
Hi

I am reaching out regarding an issue I've encountered with the plugin in Hearthstone Deck Tracker. It appears that the plugin does not retain its screen location settings upon restarting the software. Each time I reopen the Hearthstone Deck Tracker, the plugin's position is reset to its default location.

This behavior is causing inconvenience as I have to readjust the plugin's position manually every time I start the application. It would greatly enhance the user experience if the plugin could remember its screen location settings between sessions.

I appreciate your attention to this matter and kindly request assistance in resolving this issue. Please let me know if there are any troubleshooting steps I can follow or if there are plans to address this in a future update.

Thank you for your time and assistance.

Best regards,

**Comment by batstyx** [comment]
I'm assuming you're running at least [v1.12.0.3069](https://github.com/batstyx/Graveyard/releases/tag/v1.12.0.3069) if not [v1.13.0.3072](https://github.com/batstyx/Graveyard/releases/tag/v1.13.0.3072)?

Have you looked at the contents of `%appdata%\HearthstoneDeckTracker\Logs\hdt_log.txt` to see if any errors are being generated by either Graveyard or HDT itself.

[v1.11.0.3061](https://github.com/batstyx/Graveyard/releases/tag/v1.11.0.3061) introduced `%appdata%\HearthstoneDeckTracker\Plugin.Graveyard\Settings.xml` as a replacement for `%appdata%\HearthstoneDeckTrack\Graveyard.xml` and changed absolute screen positions for percentages.

Assuming your Graveyard version is more recent than this, it sounds like some part of that change may be going wrong, hopefully `hdt_log.txt` will contain an answer.

**Comment by Cyberdr3am** [comment]
I have tested the versions you suggested, namely v1.13.0.3072 and v1.12.0.3069, but unfortunately, the problem persists. Upon checking the hdt_log.txt file located at %appdata%\HearthstoneDeckTracker\Logs, I did observe some errors that could explain this behavior.

Additionally, I have attempted to resolve the issue by deleting the configuration files, but it seems this action did not resolve the problem either.

hdt_log.txt

`11:09:33 PM|Info|Core.Initialize >> HDT: 1.24.4.6563, Operating System: Windows 10 Home 22631, .NET Framework: 533320
11:09:33 PM|Info|Updater.StartupUpdateCheck >> Checking for updates
11:09:34 PM|Info|Updater.GetReleaseUrl >> Downloading releases file
11:09:34 PM|Info|Updater.GetReleaseUrl >> using 'live' release: https://github.com/HearthSim/HDT-Releases
11:09:34 PM|Info|Updater.SquirrelUpdate >> Checking for updates (ignoreDelta=False)
11:09:35 PM|Info|Updater.SquirrelUpdate >> No new updated available
11:09:35 PM|Info|SplashScreenWindow.ShowConditional >> Showing splashscreen...
23:09:35|Info|ThemeManager.LoadThemes >> Found theme: classic
23:09:35|Info|ThemeManager.LoadThemes >> Found theme: dark
23:09:35|Info|ThemeManager.LoadThemes >> Found theme: frost
23:09:35|Info|ThemeManager.LoadThemes >> Found theme: minimal
23:09:35|Info|GameV2.Reset >> -------- Reset ---------
23:09:37|Info|OverlayWindow.RunHoverUpdates >> Starting overlay hover updates...
23:09:37|Info|OverlayWindow.RunHoverUpdates >> Stopping overlay hover updates
23:09:37|Info|OverlayWindow.RunHoverUpdates >> Starting overlay hover updates...
23:09:37|Info|OverlayWindow.RunHoverUpdates >> Stopping overlay hover updates
23:09:37|Info|OverlayWindow.RunHoverUpdates >> Starting overlay hover updates...
23:09:37|Info|OverlayWindow.RunHoverUpdates >> Stopping overlay hover updates
23:09:39|Info|MainWindow.SelectDeck >> Switched to deck: Chevalier de la mort2 (v1.0)
23:09:39|Info|GameV2.Reset >> -------- Reset ---------
23:09:40|Info|BackupManager.Run >> Running BackupManager
23:09:40|Info|BackupManager.Run >> Backup for today already exists
23:09:40|Info|PluginManager.LoadPluginsFromPath >> Loading Plugins...
23:09:40|Info|PluginWrapper.Load >> Loading Arena Helper
23:09:40|Info|PluginWrapper.IsEnabled >> Enabled Arena Helper
23:09:40|Info|PluginWrapper.Load >> Loading Autosquelch
23:09:40|Info|HotKeyManager.RegisterHotkey >> Registering [mod=Alt, Control, key=D]: Toggle Autosquelch.
23:09:40|Info|PluginWrapper.IsEnabled >> Enabled Autosquelch
23:09:40|Info|PluginWrapper.Load >> Loading Graveyard
23:09:40|Warning|Settings.SettingsLoadedEventHandler >> PlayerTop loading error
23:09:40|Error|Settings.SettingsLoadedEventHandler >> System.FormatException: Le format de la chaîne d'entrée est incorrect.
   à System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   à System.String.System.IConvertible.ToDouble(IFormatProvider provider)
   à System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   à HDT.Plugins.Graveyard.Settings.SettingsLoadedEventHandler(Object sender, SettingsLoadedEventArgs e)
23:09:40|Warning|Settings.SettingsLoadedEventHandler >> EnemyLeft loading error
23:09:40|Error|Settings.SettingsLoadedEventHandler >> System.FormatException: Le format de la chaîne d'entrée est incorrect.
   à System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   à System.String.System.IConvertible.ToDouble(IFormatProvider provider)
   à System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   à HDT.Plugins.Graveyard.Settings.SettingsLoadedEventHandler(Object sender, SettingsLoadedEventArgs e)
23:09:40|Warning|Settings.SettingsLoadedEventHandler >> EnemyTop loading error
23:09:40|Error|Settings.SettingsLoadedEventHandler >> System.FormatException: Le format de la chaîne d'entrée est incorrect.
   à System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   à System.String.System.IConvertible.ToDouble(IFormatProvider provider)
   à System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   à HDT.Plugins.Graveyard.Settings.SettingsLoadedEventHandler(Object sender, SettingsLoadedEventArgs e)
23:09:40|Info|Settings.SettingsLoadedEventHandler >> C:\Users\hsx\AppData\Roaming\HearthstoneDeckTracker\Plugin.Graveyard\Settings.xml loaded
23:09:40|Info|Settings.SettingsLoadedEventHandler >> Watching C:\Users\hsx\AppData\Roaming\HearthstoneDeckTracker\Plugin.Graveyard\Settings.xml changes
23:09:40|Info|PluginWrapper.IsEnabled >> Enabled Graveyard
23:09:40|Info|Helper.EnsureClientLogConfig >> client.config is up-to-date
23:09:40|Info|Helper.GetCurrentRegion >> Region: EU
23:09:40|Info|BackupManager.Run >> Running BackupManager
23:09:40|Info|BackupManager.Run >> Backup for today already exists
23:09:40|Info|LogWatcherManager.Start >> Using Hearthstone log directory 'C:\Program Files (x86)\Hearthstone\Logs'
23:09:40|Info|LogWatcherManager.OnLogFileFound >> Achievements
23:09:40|Info|LogWatcherManager.OnLogFileFound >> LoadingScreen
23:09:40|Info|ApiWrapper.UpdateUploadTokenStatus >> Checking token status...
23:09:41|Info|Helper.EnsureClientLogConfig >> client.config is up-to-date
23:09:41|Info|HsReplayDecks.Load >> Loaded from disk: Count=1390, ServerTS=18/02/2024 15:22:17, Downloaded=18/02/2024 22:41:29 Age=00:28:12.0777014
23:09:41|Info|HsReplayDecks.Load >> Complete: Count=1390, ServerTS=18/02/2024 15:22:17, Downloaded=18/02/2024 22:41:29 Age=00:28:12.0787023
23:09:41|Info|LogWatcherManager.OnLogFileFound >> Power
23:09:41|Info|GameEventHandler.HandleGameStart >> --- Game start ---
23:09:41|Info|GameV2.Reset >> -------- Reset ---------
23:09:41|Info|GameV2.UpdatePlayers >> Exod1us#21183 [PlayerId=2] vs CoNSpiracy#21204 [PlayerId=1]
23:09:41|Info|TurnTimer.Start >> Starting turn timer
23:09:41|Warning|TurnTimer.Start >> Waiting for player entity
23:09:41|Info|TagChangeActions.SetHeroAsync >> Found hero with id=80
23:09:41|Info|GameEventHandler.SetOpponentHero >> Opponent=Warrior
23:09:41|Info|TagChangeActions.SetHeroAsync >> Found hero with id=82
23:09:41|Info|GameEventHandler.SetPlayerHero >> Player=Deathknight
23:09:41|Info|GameV2.CurrentMode >> GAMEPLAY
23:09:41|Info|GameEventHandler.HandleTurnStart >> --- Opponent turn 1 ---
23:09:41|Info|GameEventHandler.HandleTurnStart >> --- Player turn 1 ---
23:09:41|Info|GameEventHandler.HandleTurnStart >> --- Opponent turn 2 ---
23:09:41|Info|GameEventHandler.HandleOpponentHeroPower >> OpponentHeroPower (id:HERO_01dbp turn:2 from:-1)
23:09:41|Info|GameEventHandler.HandleTurnStart >> --- Player turn 2 ---
23:09:41|Info|GameEventHandler.HandleTurnStart >> --- Opponent turn 3 ---
23:09:41|Info|GameEventHandler.HandleTurnStart >> --- Player turn 3 ---
23:09:41|Info|GameEventHandler.HandleTurnStart >> --- Opponent turn 4 ---
23:09:41|Info|GameEventHandler.HandleTurnStart >> --- Player turn 4 ---
23:09:41|Info|GameEventHandler.HandlePlayerHeroPower >> PlayerHeroPower (id:HERO_11cbp turn:4 from:-1)
23:09:42|Info|GameEventHandler.HandleTurnStart >> --- Opponent turn 5 ---
23:09:42|Info|GameEventHandler.HandleOpponentHeroPower >> OpponentHeroPower (id:HERO_01dbp turn:5 from:-1)
23:09:42|Info|GameEventHandler.HandleTurnStart >> --- Player turn 5 ---
23:09:42|Info|GameEventHandler.HandleTurnStart >> --- Opponent turn 6 ---
23:09:42|Info|GameEventHandler.HandleTurnStart >> --- Player turn 6 ---
23:09:42|Info|GameEventHandler.HandlePlayerHeroPower >> PlayerHeroPower (id:HERO_11cbp turn:6 from:-1)
23:09:42|Info|GameEventHandler.HandleTurnStart >> --- Opponent turn 7 ---
23:09:42|Info|GameEventHandler.HandleTurnStart >> --- Player turn 7 ---
23:09:42|Info|GameEventHandler.HandleTurnStart >> --- Opponent turn 8 ---
23:09:42|Info|GameEventHandler.HandleTurnStart >> --- Player turn 8 ---
23:09:42|Info|GameEventHandler.HandlePlayerHeroPower >> PlayerHeroPower (id:HERO_11cbp turn:8 from:-1)
23:09:42|Info|GameEventHandler.HandleTurnStart >> --- Opponent turn 9 ---
23:09:42|Info|GameEventHandler.HandleTurnStart >> --- Player turn 9 ---
23:09:42|Info|GameEventHandler.HandlePlayerHeroPower >> PlayerHeroPower (id:HERO_11cbp turn:9 from:-1)
23:09:42|Info|GameEventHandler.HandleTurnStart >> --- Opponent turn 10 ---
23:09:42|Info|ApiWrapper.UpdateUploadTokenStatus >> Token is not claimed
23:09:46|Info|OverlayWindow.RunHoverUpdates >> Starting overlay hover updates...
23:09:46|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
23:09:46|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 19 tries.
23:09:46|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 20 tries.
23:09:50|Info|OverlayWindow.RunHoverUpdates >> Stopping overlay hover updates
23:09:50|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
23:10:18|Info|GameEventHandler.HandleTurnStart >> --- Player turn 10 ---
23:10:23|Info|OverlayWindow.RunHoverUpdates >> Starting overlay hover updates...
23:10:23|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
23:10:38|Info|GameEventHandler.HandlePlayerHeroPower >> PlayerHeroPower (id:HERO_11cbp turn:10 from:-1)
23:10:41|Info|OverlayWindow.RunHoverUpdates >> Stopping overlay hover updates
23:10:41|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
23:10:41|Info|GameEventHandler.HandleTurnStart >> --- Opponent turn 11 ---
23:10:43|Info|OverlayWindow.RunHoverUpdates >> Starting overlay hover updates...
23:10:43|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
23:10:44|Info|OverlayWindow.RunHoverUpdates >> Stopping overlay hover updates
23:11:06|Info|GameEventHandler.HandleTurnStart >> --- Player turn 11 ---
23:11:29|Info|OverlayWindow.RunHoverUpdates >> Starting overlay hover updates...
23:11:29|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
23:11:39|Info|OverlayWindow.RunHoverUpdates >> Stopping overlay hover updates
23:11:39|Info|GameEventHandler.HandleTurnStart >> --- Opponent turn 12 ---
23:12:09|Info|GameEventHandler.HandleTurnStart >> --- Player turn 12 ---
23:12:16|Info|OverlayWindow.RunHoverUpdates >> Starting overlay hover updates...
23:12:16|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
23:12:17|Info|AssetDownloader.DownloadAsset >> Starting download for REV_957.png.
23:12:17|Info|AssetDownloader.DownloadFileAsync >> Waiting to cleanup REV_957.png.
23:12:30|Info|OverlayWindow.RunHoverUpdates >> Stopping overlay hover updates
23:12:33|Info|GameEventHandler.HandleTurnStart >> --- Opponent turn 13 ---
23:13:44|Info|GameEventHandler.HandleTurnStart >> --- Player turn 13 ---
23:13:47|Info|GameEventHandler.HandleWin >> --- Game was won! ---
23:13:47|Info|TurnTimer.Stop >> Stopping turn timer
23:13:47|Info|GameEventHandler.HandleGameEnd >> Game ended...
23:13:47|Info|GameEventHandler.HandleGameEnd >> Format: Standard
23:13:47|Info|GameStats.GameEnd >> Current Game ended after 13 turns
23:13:47|Info|GameEventHandler.HandleGameEnd >> Assigned current game to deck: Chevalier de la mort2
23:13:47|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
23:13:47|Info|LogUploader.Upload >> Uploading 927699983...
23:13:47|Info|LogUploader.TryUpload >> Creating upload request...
23:13:47|Info|LogUploader.TryUpload >> Upload Id: J6w94cyJe9jExaaJ2SgJdh
23:13:48|Info|LogUploader.TryUpload >> Upload complete
23:13:49|Info|LogUploader.Upload >> 927699983 complete. Success=True
23:17:24|Info|Strings.GetLocalized >> Local Deathknight string not available, trying to use HDT string instead
23:17:24|Info|Strings.GetLocalized >> Local DemonHunter string not available, trying to use HDT string instead
23:17:24|Info|Strings.GetLocalized >> Local Druid string not available, trying to use HDT string instead
23:17:24|Info|Strings.GetLocalized >> Local Hunter string not available, trying to use HDT string instead
23:17:24|Info|Strings.GetLocalized >> Local Mage string not available, trying to use HDT string instead
23:17:24|Info|Strings.GetLocalized >> Local Paladin string not available, trying to use HDT string instead
23:17:24|Info|Strings.GetLocalized >> Local Priest string not available, trying to use HDT string instead
23:17:24|Info|Strings.GetLocalized >> Local Rogue string not available, trying to use HDT string instead
23:17:24|Info|Strings.GetLocalized >> Local Shaman string not available, trying to use HDT string instead
23:17:24|Info|Strings.GetLocalized >> Local Warlock string not available, trying to use HDT string instead
23:17:24|Info|Strings.GetLocalized >> Local Warrior string not available, trying to use HDT string instead
23:17:24|Info|Strings.GetLocalized >> Local Neutral string not available, trying to use HDT string instead
23:17:31|Info|OverlayWindow.RunHoverUpdates >> Starting overlay hover updates...
23:17:31|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
23:17:31|Info|AssetDownloader.DownloadAsset >> Starting download for TTN_811.png.
23:17:31|Info|AssetDownloader.DownloadFileAsync >> Waiting to cleanup TTN_811.png.
23:17:33|Info|OverlayWindow.RunHoverUpdates >> Stopping overlay hover updates
23:17:34|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
23:17:36|Info|OverlayWindow.RunHoverUpdates >> Starting overlay hover updates...
23:17:36|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
23:17:38|Info|OverlayWindow.RunHoverUpdates >> Stopping overlay hover updates
23:17:38|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
23:17:43|Info|OverlayWindow.RunHoverUpdates >> Starting overlay hover updates...
23:17:43|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
23:17:44|Info|OverlayWindow.RunHoverUpdates >> Stopping overlay hover updates
23:17:44|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
23:17:47|Info|OverlayWindow.RunHoverUpdates >> Starting overlay hover updates...
23:17:47|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
23:17:47|Info|OverlayWindow.RunHoverUpdates >> Stopping overlay hover updates
23:17:47|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
23:17:49|Info|OverlayWindow.RunHoverUpdates >> Starting overlay hover updates...
23:17:49|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
23:17:51|Info|OverlayWindow.RunHoverUpdates >> Stopping overlay hover updates
23:17:51|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
23:17:54|Info|OverlayWindow.RunHoverUpdates >> Starting overlay hover updates...
23:17:54|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
23:17:54|Info|OverlayWindow.RunHoverUpdates >> Stopping overlay hover updates
23:17:55|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
23:17:58|Info|OverlayWindow.RunHoverUpdates >> Starting overlay hover updates...
23:17:58|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
23:17:58|Info|OverlayWindow.RunHoverUpdates >> Stopping overlay hover updates
23:17:58|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
23:18:03|Info|OverlayWindow.RunHoverUpdates >> Starting overlay hover updates...
23:18:03|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
23:18:04|Info|OverlayWindow.RunHoverUpdates >> Stopping overlay hover updates
23:18:04|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
23:18:07|Info|OverlayWindow.RunHoverUpdates >> Starting overlay hover updates...
23:18:07|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
23:18:07|Info|OverlayWindow.RunHoverUpdates >> Stopping overlay hover updates
23:18:07|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
23:18:09|Info|OverlayWindow.RunHoverUpdates >> Starting overlay hover updates...
23:18:09|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
23:18:10|Info|OverlayWindow.RunHoverUpdates >> Stopping overlay hover updates
23:18:10|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
23:18:12|Info|OverlayWindow.RunHoverUpdates >> Starting overlay hover updates...
23:18:12|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
23:18:14|Info|OverlayWindow.RunHoverUpdates >> Stopping overlay hover updates
23:18:14|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
23:18:28|Info|MainWindow.Window_Closing >> Shutting down...
23:18:28|Info|HotKeyManager.RemovePredefinedHotkey >> Removing [mod=Alt, Control, key=D].
23:18:28|Error|XmlManager.Save >> System.UnauthorizedAccessException: L'accès au chemin d'accès est refusé.
   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.__Error.WinIOError()
   à System.IO.File.InternalReplace(String sourceFileName, String destinationFileName, String destinationBackupFileName, Boolean ignoreMetadataErrors)
   à System.IO.File.Replace(String sourceFileName, String destinationFileName, String destinationBackupFileName)
   à Hearthstone_Deck_Tracker.XmlManager`1.Save(String path, Object obj) dans D:\a\Hearthstone-Deck-Tracker\Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\Utility\XmlManager.cs:ligne 48
23:18:28|Info|Settings.SettingsSavingEventHandler >> C:\Users\hsx\AppData\Roaming\HearthstoneDeckTracker\Plugin.Graveyard\Settings.xml saved
`

**Comment by batstyx** [comment]
You're log errors being en Francais are also a big clue!

I've managed to replicate the issue and it's a classic comma/full stop as decimal point conversion error.
It appears to be an HDT related bug rather than anything to do with the underlying OS language and format settings.

If HDT is set to French (options->Tracker-Appearance->Language: French), Graveyard will save the values in "English" format (full stop as decimal point) but then try and read them in "French" format (comma as decimal point), causing an error on each value and failing to read them. I'm guessing this error will also occur in any language that doesn't use a full stop as a decimal point.

Until I can determine how best to fix it, I suggest a couple of workarounds:-

1. By switching HDT to English (apologies for even suggesting ;)
2. By editing `%appdata%\HearthstoneDeckTracker\Plugin.Graveyard\Settings.xml`
  a. Use HDT to set the positions you want
  b. Close HDT
  c. Open `%appdata%\HearthstoneDeckTracker\Plugin.Graveyard\Settings.xml` in Notepad or similar
  d. Change `.` to `,` for `PlayerLeft`, `PlayerTop`, `EnemyLeft`, `EnemyTop` values (changing them to whole numbers will also work and is probably a better option)
  As long as you don't change the values in HDT after that you shouldn't have a problem.

**Comment by batstyx** [comment]
[v1.13.1.3073](https://github.com/batstyx/Graveyard/releases/tag/v1.13.1.3073) should fix your issue without any need for a workaround 
(although if you've already done 2. d. you'll need to revert any `,` to `.`)
