### ISSUE TITLE
How to set this plugin's layout?

### ISSUE THREAD

**Issue by ZelKnow** [batstyx/Graveyard#5]
I think the layout is supposed to be settable.
And I cannot open the plugin's settings
![QQ截图20200428224807](https://user-images.githubusercontent.com/39847007/80505926-8ad54d80-89a7-11ea-9ca5-76c15be733b2.png)

**Comment by batstyx** [comment]
In Hearthstone Deck Tracker -> Options
Tracker -> Plugins -> Graveyard -> 'Settings' button
Press 'Unlock Graveyards' button. It should change to 'Lock Graveyards'
In-game, drag the Friendly and Opponent windows to where you want them.
You can lock graveyards again to avoid accidentally moving the windows but it will reset to locked the next time you start HDT anyway.

**Comment by chWolfgang** [comment]
With the changes to HSDT with 1.11.6 (which was downloadable and now is a release) I can not get to settings any more. Click it and nothing happens. However, it does seem to be working with existing settings.

**Comment by batstyx** [comment]
[Release v1.8: Hearthstone Deck Tracker 1.11](https://github.com/batstyx/Graveyard/releases/tag/v1.8)

**Comment by batstyx** [comment]
@ZelKnow26 I've added localization support to the plugin. Can I include your [translation](https://github.com/ZelKnow26/Graveyard/blob/batstyx/Graveyard/Resources/Strings.resx) please?
