### ISSUE TITLE
Trying to move a “scaling” slider crashes HDT while overlay is unlocked

### ISSUE THREAD

**Issue by alterNERDtive** [batstyx/Graveyard#6]
1. go to options → plugins → graveyard → settings
1. hit “unlock graveyards”
1. use either of the “scale” sliders
1. HDT crashes

Works fine while the overlay is locked

**Comment by alterNERDtive** [comment]
Well that’s what I could call a quick fix :)

**Comment by batstyx** [comment]
Luckily there was an easy fix. A lot of changes I've wanted to make in the past have come down to "yeah, that's not how it works, you'd need a complete re-write" so haven't got any further.
