### ISSUE TITLE
Settings button

### ISSUE THREAD

**Issue by similarion** [batstyx/Graveyard#8]
I'm trying to move the Resurrect overlay by opening the settings of the Graveyard plugin but when I press the settings button in the plugins page of HDT, nothing happens. Any idea?

**Comment by batstyx** [comment]
What versions of HDT and Graveyard are you using? It opens the settings for me with the latest HDT (1.13.25) and most recent Graveyard (1.8.9 and 1.8.10).
If you look at `%appdata%\HearthstoneDeckTracker\Logs\hdt_log.txt` after pressing the Graveyard settings button is there any obvious error?
You could try removing or renaming `%appdata%\HearthstoneDeckTracker\Graveyard.xml` to reset the plugin to it's default config (with HDT closed).
