### ISSUE TITLE
how to embed your version in hsreplay

### ISSUE THREAD

**Issue by nadoissandre** [batstyx/Graveyard#9]
Hello
I would like to benefit from your follow-up of the cemetery plugin for hsreplay but how I can put it in my replay tool I downloaded your files but there is no dll
thank you so much

**Comment by batstyx** [comment]
I'm not sure what you mean exactly, each [release](https://github.com/batstyx/Graveyard/releases/tag/v1.8.11.57) has a [Graveyard.zip](https://github.com/batstyx/Graveyard/releases/download/v1.8.11.57/Graveyard.zip) file containing the Graveyard.dll plugin in 'Assets'. 
I don't know what hsreplay is, so I can't comment further than that on how you might use the file.

**Comment by nadoissandre** [comment]
thanks you it is ok
